export default {

    ADD_POSTS: "ADD_POSTS",
    ADD_POSTS_PENDING: "ADD_POSTS_PENDING",
    ADD_POSTS_FULFILLED: "ADD_POSTS_FULFILLED",
    ADD_POSTS_REJECTED: "ADD_POSTS_REJECTED",

    GET_POSTS: "GET_POSTS",
    GET_POSTS_PENDING: "GET_POSTS_PENDING",
    GET_POSTS_FULFILLED: "GET_POSTS_FULFILLED",
    GET_POSTS_REJECTED: "GET_POSTS_REJECTED",

    ADD_USER: "ADD_USER",
    ADD_USER_PENDING: "ADD_USER_PENDING",
    ADD_USER_FULFILLED: "ADD_USER_FULFILLED",
    ADD_USER_REJECTED: "ADD_USER_REJECTED",

    GET_USER: "GET_USER",
    GET_USER_PENDING: "GET_USER_PENDING",
    GET_USER_FULFILLED: "GET_USER_FULFILLED",
    GET_USER_REJECTED: "GET_USER_REJECTED",

    GET_USERS: "GET_USERS",
    GET_USERS_PENDING: "GET_USERS_PENDING",
    GET_USERS_FULFILLED: "GET_USERS_FULFILLED",
    GET_USERS_REJECTED: "GET_USERS_REJECTED",

    GET_USERNAME: "GET_USERNAME",
    GET_USERNAME_PENDING: "GET_USERNAME_PENDING",
    GET_USERNAME_FULFILLED: "GET_USERNAME_FULFILLED",
    GET_USERNAME_REJECTED: "GET_USERNAME_REJECTED"

}